### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lasselukkari**

### CODE REVIEW

**Comment by orktes** [comment]
Awesome work! Now just sit back and wait for Travis to pass and others to review your code.

## Reviewers

@orktes
- README.md

### Review commands
- accept: `pr_review OK`
- add reviewer: `pr_review add [username]`
- change reviewer: `pr_review change [old_username] [new_username]`
- print status: `pr_review status`

**Comment by orktes** [comment]
pr_status ok

**Comment by orktes** [comment]
pr_review ok

**Comment by orktes** [comment]
Review completed!

**Comment by lasselukkari** [comment]
pr_review status

**Comment by orktes** [comment]
Waiting review from

**Comment by orktes** [comment]
Review completed!

**Comment by lasselukkari** [comment]
pr_review add orktes

**Comment by lasselukkari** [comment]
pr_review status

**Comment by orktes** [comment]
Waiting review from

@orktes

**Pull request closed without merging**
